### ISSUE TITLE
Add download storage explorer to Lab0

### ISSUE THREAD

**Issue by DOMZE** [MSDEVMTL/GlobalAzureBootcamp-2019#11]
Add the following text (and more possibly) to lab0 setup:

**Download Azure Storage Explorer**

If you are not using the Azure Portal, you can download the Azure Storage Explorer [here](https://azure.microsoft.com/en-ca/features/storage-explorer/). 

Once you have Azure Storage Explorer, add your account and you should be able to see all the storage in your (selected) subscription(s)

**Comment by Carl-Hugo** [comment]
Since we are using VS Code, we could also recommend the following extension: [Azure Storage](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage) as a complement or instead.

**Comment by fboucher** [comment]
Done.
@DOMZE  I added the steps in Lab0
