### ISSUE TITLE
In Lab 1 - fix Git code

### ISSUE THREAD

**Issue by fboucher** [MSDEVMTL/GlobalAzureBootcamp-2019#22]
In the section [Initialize Local Repository](https://github.com/MSDEVMTL/GlobalAzureBootcamp-2019/tree/master/Lab1#initialize-local-repository)

the code is wrong:

     git add -A -m "initial commit"  (i dont think that this command works --> should be git add . or git add  -A than you can use git commit -m "initial commit")

**Comment by alainvezina** [comment]
I fixed it
