### ISSUE TITLE
How to open a terminal on Mac?

### ISSUE THREAD

**Issue by Carl-Hugo** [MSDEVMTL/GlobalAzureBootcamp-2019#29]
@MSDEVMTL/gab2019-contributors 
In lab 3 I explain a few ways to open a terminal on Windows, but I have no clue how to open one with a MAC (sorry Apple I am not a customer of yours). For Linux, we could guess that the user knows.

Does any of you know how macs work, so I could replace `TODO: how to do that?` by more precise instructions? Thanks

**Comment by fboucher** [comment]
http://bfy.tw/N9vF
😜

**Comment by Carl-Hugo** [comment]
And there goes your yearly bonus! Recommending me Google instead of Bing 😮 

Found it!

![Old terminal](http://toastytech.com/guis/auxcompile1.png)

Seriously, I guess I'll do that
