### ISSUE TITLE
Lab 2 - Indentation needs to be fixed

### ISSUE THREAD

**Issue by fboucher** [MSDEVMTL/GlobalAzureBootcamp-2019#39]
Indentation needs to be fixed. Nothing crazy but the steps 1,2,3,4... aren't the things at that are at the extreme left. code, text, and images are...

**Comment by arribajuan** [comment]
I fixed some indentation issues on lab 2 as part of another ticket.

The results can be seen in this PR: https://github.com/MSDEVMTL/GlobalAzureBootcamp-2019/pull/58

If the changes are good, we could close this issue.
