### ISSUE TITLE
Lab 2 - Part 2 - Deploy automatically your first template is NOT DONE

### ISSUE THREAD

**Issue by fboucher** [MSDEVMTL/GlobalAzureBootcamp-2019#40]
In the section Deploy automatically your first template (https://github.com/MSDEVMTL/GlobalAzureBootcamp-2019/tree/master/Lab2#part-2---deploy-automatically-your-first-template)

multiple steps are missing. We need to complete this LAB

**Comment by alainvezina** [comment]
Its done
