### ISSUE TITLE
Lab 3 - Where should we create the files?

### ISSUE THREAD

**Issue by fboucher** [MSDEVMTL/GlobalAzureBootcamp-2019#41]
it's not clear where we should create the files:  `Dockerfile`  and `.dockerignore`

From the screenshot, it looks at inside folder gab2019 but the folder structure is different from Lab 1 and Lab2.

**Comment by Carl-Hugo** [comment]
I will revise this as soon as possible and make sure to clarify the location of the `Dockerfile` and `.dockerignore` files.
