### ISSUE TITLE
Confusion between folder named GABDemo and GABCDemo

### ISSUE THREAD

**Issue by fboucher** [MSDEVMTL/GlobalAzureBootcamp-2019#56]
Confusion between folder named GABDemo and GABCDemo

**Comment by DOMZE** [comment]
Which one would you suggest?

**Comment by fboucher** [comment]
GABCDemo
Global Azure BootCamp

**Comment by alainvezina** [comment]
I think it should be GAB since it Global Azure Bootcamp... not BootCamp  .. a single word... Maybe I'm wrong here ! My wife say, that I'm always wrong ... so .. :

Can you double check .. because otherwise I will apply your suggestion

**Comment by fboucher** [comment]
Go for **GAB**

**Comment by alainvezina** [comment]
So im moving lab 2 to GABDemo

**Comment by alainvezina** [comment]
Also the resource group , app plan etc.. everything that was gabc is now gab in lab 1 and lab 2

**Comment by DOMZE** [comment]
Ok I had renamed, but reverted. GABDemo it is

Thanks @alainvezina @FBoucher
