### ISSUE TITLE
Lab1 - specify to use a unique name for this command

### ISSUE THREAD

**Issue by mbernard** [MSDEVMTL/GlobalAzureBootcamp-2019#60]
Specify that we should use a unique name as it's use as a dns record. If everybody try to use this one, only the first person will be able to create it
`az webapp create --name gabcdemo --resource-group gabcdemogroup --plan gabcdemoplan`

**Comment by fboucher** [comment]
It's already explained.

> Note: You might experience an error if you webapp name is not unique. (Conflict: Website with given name <web app name> already exists.) Make sure to use a unique name. ex: gab2019<your_initial><2digits_random_number> gab2019AV47


@mbernard  Did you mean anything else?

**Comment by mbernard** [comment]
oupsss I read it to guickly I guess. My bad
