### ISSUE TITLE
Lab5 - Typos

### ISSUE THREAD

**Issue by mbernard** [MSDEVMTL/GlobalAzureBootcamp-2019#64]
- when talking about the interface `IBlobStorageManager`, it says `BlobStorageManager ` without the `I`
- A bit later it says `IBlobStorageManager` should be `IImageAnalyzer`
- This typo appears a couple time `Blog` instead of `Blob`

**Comment by DOMZE** [comment]
Good catch @mbernard !

I fixed and pushed my changes. Please look in case i missed anything. I also recreated the folder layout because of the typo `blog`

**Comment by mbernard** [comment]
@DOMZE I fixed the last one. I think everything else is good
